let number = randint(1, 5)
if (number == 1) {
    turtle.pen(TurtlePenMode.Down)
    turtle.setPosition(2, 2)
    turtle.setBrightness(255)
    turtle.forward(2)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(2)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(3)
    turtle.turnLeft()
    turtle.forward(1)
    basic.clearScreen()
    basic.pause(100)
    basic.showString("UMBRELLA")
} else if (number == 2) {
    turtle.pen(TurtlePenMode.Down)
    turtle.setPosition(2, 2)
    turtle.setBrightness(255)
    turtle.turnRight()
    turtle.forward(2)
    turtle.turnRight()
    turtle.turnRight()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnRight()
    turtle.forward(2)
    turtle.turnRight()
    turtle.forward(3)
    turtle.turnRight()
    turtle.forward(1)
    turtle.turnRight()
    turtle.forward(1)
    turtle.turnRight()
    turtle.forward(2)
    basic.pause(100)
    basic.clearScreen()
    basic.showString("DUCK")
} else if (number == 3) {
    turtle.pen(TurtlePenMode.Down)
    turtle.setPosition(4, 2)
    turtle.setBrightness(225)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(2)
    turtle.turnRight()
    turtle.forward(2)
    turtle.turnRight()
    turtle.forward(3)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(1)
    basic.pause(100)
    basic.clearScreen()
    basic.showString("SNAKE")
} else if (number == 4) {
    turtle.pen(TurtlePenMode.Down)
    turtle.setBrightness(225)
    turtle.setPosition(3, 4)
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(2)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.turnLeft()
    turtle.forward(4)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(1)
    basic.pause(100)
    basic.clearScreen()
    basic.showString("GIRRAFE")
} else if (number == 5) {
    turtle.pen(TurtlePenMode.Down)
    turtle.setPosition(4, 2)
    turtle.setBrightness(255)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnRight()
    turtle.turnRight()
    turtle.forward(2)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnRight()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.turnLeft()
    turtle.forward(2)
    turtle.turnLeft()
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnRight()
    turtle.forward(1)
    basic.pause(100)
    basic.clearScreen()
    basic.showString("TURTLE")
}
